---
- name : installation nginx
  hosts: 192.168.88.144
  vars :
   user : cgo
   domains :
      
    - domain: ta.fr
      php: yes
    - domain: to.com
      php: no

  roles :
   - tools
   - user
   - nginxv2