---
# tasks file for nginx
- name:
  become : yes
  apt : name=nginx state=latest

- name : start
  become: yes
  service: name=nginx state=started enabled=true

- name : sup default
  become : yes
  file : path=/etc/nginx/sites-enabled/default state=absent force=yes
  notify : restart nginx

- name : configuration des sites
  include  : sites.yml
  with_items : "{{ domains }}"
  

- name : installation php
  include : php.yml
  with_items : "{{ php_packages }}"