- name : installation de php
  apt : name={{ item }} state=present
  

- name : "configuration de php : uploadMax"
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '^upload_max_filesize = '
    line: upload_max_filesize = {{ php_upload_max_filesize }}
    
    

- name : "configuration de php : date&timezone"
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regexp: 'date.timezone'
    line: date.timezone = {{ php_timezone }}

    

- name : "configuration de php : memory limit"
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '^memory_limit = '
    line: memory_limit = {{ php_memory_limit }}
    
- name : "configuration de php : postmaxsize"
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '^post_max_size = '
    line: post_max_size = {{ php_post_max_size }}


  
    
