- name : crea du dossier
  become : yes
  file : path=/home/{{ user }}/{{ item.domain }} state=directory owner={{ user }} group={{ user }}

- name : lien vers www
  become : yes
  file : src=/home/{{ user }}/{{ item.domain }} dest=/var/www/{{ item.domain }} state=link
  notify : restart nginx

- name : creation conf nginx
  template : src=nginx.j2 dest=/etc/nginx/sites-available/{{ item.domain }} 


- name : activation du domain
  file : src=/etc/nginx/sites-available/{{ item.domain }} dest=/etc/nginx/sites-enabled/{{ item.domain }} state=link
  
