---
- name: "Installation du service nginx"
  hosts: 192.168.88.138
  vars:
    user: ajc
  tasks:


   - name: "Installation tools"
     yum: name={{ item }} update_cache=yes state=latest
     with_items:
       - git
       - zsh 
       - sudo

   - name: "Creation de user"{{ user }}
     when: user is defined
     user: name={{ user }} comment="master" shell=
   - name: ajout cle ssh
     when: user is defined
     authorized_key: user={{ user }}  key: "{{ lookup('file', '/root/.ssh/id_rsa.pub')}}"     
     
     
