---
- hosts: local 
  connection: local 
  gather_facts: False
  vars:
    instance_name: ronyDEB
    instance_type: t3.large
    security_group: secur_test_rony
    image: ami-00a845a11b3d1f308
    keypair: BRAZIL  
    region: eu-west-1
    count: 1
  vars_files:
    - /home/works/aws_keys.yml
    
  
  tasks:
     
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: The webservers security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
            
    - name: Launch the new EC2 Instance
      ec2:
        key_name: rony_instance
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true 
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{count}}"
      register: ec2
      
    - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
      local_action: wait_for 
                    host={{ item.public_ip }} 
                    port=22 
                    state=started
      with_items: '{{ ec2.instances }}'
        
    - name: Add tag to Instance(s)
      local_action: ec2_tag resource={{ item.id }} region={{ region }} aws_access_key={{ aws_access_key }} aws_secret_key={{ aws_secret_key }} state=present
      with_items: '{{ ec2.instances }}'
      args:
         tags:
            Name: '{{ instance_name }}' 
