---
# tasks file for mysql
#
#
- name: "Mise à jour des packages"
  become: yes
  apt:
    update_cache: yes



- name: "Installation de mysql"
  become: yes
  apt:
    name: mysql-server
    state: latest

- name: "Installation du module python"
  become: yes
  apt:
    name: python-mysqldb
    state: latest

- name: "Demmarage de mysql"
  become: yes
  service: name=mysql state=started enabled=true   
  
- name: "Installation de PIP"
  become: yes
  apt:
    name: python-pip
    state: latest
    
    
- name: "Install outils"
  become: yes
  apt:
    name: python-dev
    state: latest
    
- name: "Install outil"
  become: yes
  apt:
    name: libmysqlclient-dev
    state: latest
    
- name: "Install Mysql-python"
  become: yes
  pip:
    name: MySQL-python            
