---
# handlers file for nginxv2

- name: restart nginx
  service:
     name: nginx
     state: restarted
     
     
- name: restart php
  service:
     name: php7.3-fpm
     state: restarted
     
     